export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';

export const API_FETCH_START = 'API_FETCH_START';
export const API_FETCH_STOP = 'API_FETCH_STOP';

export const GET_ACCOUNT_INFORMATION_SUCCESS = 'GET_API_SUCCESS';
export const GET_PLAYLISTS_SUCCESS = 'GET_PLAYLISTS_SUCCESS';
export const GET_PLAYLIST_SUCCESS = 'GET_PLAYLIST_SUCCESS';

